# Generated by Django 5.2.1 on 2025-05-25 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_project_active_alter_issue_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='contributor',
            new_name='user',
        ),
    ]
