# Generated by Django 5.2.1 on 2025-05-25 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_contributor_active_alter_project_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='user',
            new_name='contributor_user',
        ),
    ]
