# Generated by Django 5.2.1 on 2025-05-26 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_rename_user_contributor_contributor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='contributor_user',
            new_name='username',
        ),
    ]
